# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/eole-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Lint/Commitlint.yaml

variables:
  # `ci-tools` default branch is `stable`
  STABLE_BRANCH: master

stages:
  - initial-checks


###############################################################################
# `initial-checks` stage: `commitlint`
###############################################################################
# Execute `commitlint` before resource heavy jobs
commitlint:
  stage: initial-checks
