# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/eole-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Lint/Commitlint.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Release/Semantic-release.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Docker.yaml

variables:
  # `ci-tools` default branch is `stable`
  STABLE_BRANCH: master
  IMAGE_NAME: eoleget

stages:
  - initial-checks
  - build
  - release


###############################################################################
# `initial-checks` stage: `commitlint`
###############################################################################
# Execute `commitlint` before resource heavy jobs
commitlint:
  stage: initial-checks


###############################################################################
# `build` stage: `*-docker-build`
###############################################################################
# Build on release tag and every branches except for `$STABLE_BRANCH`
# used only to create the release tag.
#
# The ordering is important:
# 1. exclude schedules and drafts
# 2. include `on-release-tag` which must match before `not-on-semantic-release-commit`
# 3. we exclude stable which just produce the release tag
# 4. we exclude `semantic-release` commits like when merging `release` on `dev`
# 5. run on every branches
build-docker:
  extends: .build-docker-image
  rules:
    - !reference [.rules-map, not-on-schedule]
    - !reference [.rules-map, not-on-draft]
    - !reference [.rules-map, on-release-tag]
    - !reference [.rules-map, not-on-stable]
    - !reference [.rules-map, not-on-semantic-release-commit]
    - !reference [.rules-map, on-branch]


###############################################################################
# `release` stage: `semantic-release`, `tag *`
###############################################################################
## tag contribution branches with a more stable name than `git-${CI_COMMIT_SHORT_SHA}`
tag contrib branch:
  extends:
    - .tag-docker-image
    - .on-branches
  variables:
    # `feature/foo-bar_quux` → `feature-foo-bar-quux`
    IMAGE_TAG: $CI_COMMIT_REF_SLUG

## dev images
tag dev:
  extends:
    - .tag-docker-image
    - .on-dev
  variables:
    IMAGE_TAG: dev

## testing images
tag testing:
  extends:
    - .tag-docker-image
    - .on-testing
  variables:
    IMAGE_TAG: testing

## stable images
tag release:
  extends: .tag-docker-image

tag major:
  extends: .tag-docker-image
  before_script:
    - export RELEASE_PREFIX=${RELEASE_PREFIX:-release/}
    - export RELEASE=${CI_COMMIT_TAG#${RELEASE_PREFIX}}
    - export IMAGE_TAG=${RELEASE%%.*}

tag minor:
  extends:
    - .tag-docker-image
  before_script:
    - export RELEASE_PREFIX=${RELEASE_PREFIX:-release/}
    - export RELEASE=${CI_COMMIT_TAG#${RELEASE_PREFIX}}
    - export IMAGE_TAG=${RELEASE%.${RELEASE##*.}}

tag stable:
  extends: .tag-docker-image
  variables:
    IMAGE_TAG: stable

tag latest:
  extends: .tag-docker-image
  variables:
    IMAGE_TAG: latest
