# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: commitlint
        name: Check commit message using commitlint
        description: Lint commit message against @commitlint/config-conventional rules
        stages: [commit-msg]
        language: docker_image
        entry: hub.eole.education/eole/commitlint:latest commitlint --edit
      - id: meteor:lint
        name: Lint meteor code
        description: Lint javascript code with 'meteor npm run eslint'
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        language: docker_image
        entry: |
          hub.eole.education/proxyhub/geoffreybooth/meteor-base:2.7.1
          env HOME=/tmp bin/pre-commit-meteor-lint
