version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      EOLEGET_IMAGES_FOLDER: "/opt/bundle/bundle/programs/web.browser/app/images/appli/"
      METEOR_SETTINGS: ${METEOR_SETTINGS}
  cron:
    build:
      context: .
      dockerfile: Dockerfile.eoleget-cron
    environment:
      MONGO_URL: mongodb://mongo:27017/meteor
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
